name: Les quais
markdown: kramdown
highlighter: false
# baseurl: /

collections:
  bateaux:
    output: true
  mots:
    output: true
  meta:
    output: true

defaults:
  -
    scope:
      path: ""	# means "all files"
      type: "bateaux"	# targets a collection
    values:
      layout: "boat"
  -
    scope:
      path: ""	# means "all files"
      type: "meta"	# targets a collection
    values:
      layout: "meta"
  -
    scope:
      path: ""	# means "all files"
      type: "mots"	# targets a collection
    values:
      layout: "meta"
      additional_css: "word"

description: Une œuvre de Suzanne Hetzel et Jean Schneider pour le collège Jean Jaurés à La Ciotat (Bouches-du-Rhône).
